### ISSUE TITLE
Example in MVC6

### ISSUE THREAD

**Issue by gordon-matt** [nojaf/SlidingNinthLantern#1]
Good work. However, I couldn't get it to work on VS2015 in an MVC6 project. Would you be able to provide such an example?

**Comment by nojaf** [comment]
Hi,
I haven't done much ASP NET 5 stuff yet. Do you any particular errors?
Or perhaps a project you can take a look at?

**Comment by gordon-matt** [comment]
Hi, thanks for the reply, but don't worry about it; I finally managed to get the skeleton working in MVC6 last night. I am struggling now to figure out how to make it work with an unknown number of routes (dynamically due to plugins, etc) and with razor files. If I manage to do this, I will write some how-to guide to help everyone out. But it may be a while, since the learning curve is really steep for me right now having never been big on the frontend stuff. With MVC6 focusing more on frontend development, now's certainly the time though...  :-)
